# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField(db_index=True)),
                ('priorities', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=75)),
                ('entry_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=24)),
                ('value', models.TextField(default='')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Expression')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=75)),
                ('entry_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=24)),
                ('value', models.TextField(default='')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Reading')),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pos', models.CharField(default='', max_length=100)),
                ('entry_id', models.IntegerField(db_index=True)),
                ('sense_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='SenseAntonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_text', models.TextField(db_index=True)),
                ('read_text', models.TextField(db_index=True)),
                ('sense_id', models.IntegerField(null=True)),
                ('base_text', models.TextField(db_index=True)),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Association')),
                ('base_sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_bs', to='quiz.Sense')),
            ],
        ),
        migrations.CreateModel(
            name='SenseCrossRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_text', models.TextField(db_index=True)),
                ('read_text', models.TextField(db_index=True)),
                ('sense_id', models.IntegerField(null=True)),
                ('base_text', models.TextField(db_index=True)),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Association')),
                ('base_sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_bs', to='quiz.Sense')),
            ],
        ),
        migrations.CreateModel(
            name='SenseKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=24)),
                ('value', models.TextField(default='')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Sense')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sense',
            unique_together=set([('text', 'entry_id'), ('sense_id', 'entry_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together=set([('text', 'entry_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together=set([('text', 'entry_id')]),
        ),
        migrations.AddField(
            model_name='association',
            name='expression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Expression'),
        ),
        migrations.AddField(
            model_name='association',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Reading'),
        ),
        migrations.AddField(
            model_name='association',
            name='sense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Sense'),
        ),
        migrations.AlterIndexTogether(
            name='sensekeyvalue',
            index_together=set([('key', 'sense')]),
        ),
        migrations.AlterUniqueTogether(
            name='sensecrossref',
            unique_together=set([('association', 'base_sense', 'base_text'), ('exp_text', 'read_text', 'sense_id', 'base_sense', 'base_text')]),
        ),
        migrations.AlterUniqueTogether(
            name='senseantonym',
            unique_together=set([('association', 'base_sense', 'base_text'), ('exp_text', 'read_text', 'sense_id', 'base_sense', 'base_text')]),
        ),
        migrations.AlterIndexTogether(
            name='readingkeyvalue',
            index_together=set([('key', 'reading')]),
        ),
        migrations.AlterIndexTogether(
            name='expressionkeyvalue',
            index_together=set([('key', 'expression')]),
        ),
        migrations.AlterUniqueTogether(
            name='association',
            unique_together=set([('expression', 'reading', 'sense')]),
        ),
        migrations.AlterIndexTogether(
            name='association',
            index_together=set([('expression', 'reading')]),
        ),
    ]
