# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 02:09
from __future__ import unicode_literals

from django.db import migrations, models


def update_associations(apps, schema_editor):
    Association = apps.get_model("quiz", "Association")
    Reading = apps.get_model("quiz", "Reading")
    Sense = apps.get_model("quiz", "Sense")
    Expression = apps.get_model("quiz", "Expression")

    num_total = Association.objects.count()
    counter = 0
    for assoc in Association.objects.all():
        if not counter % 100:
            print("%s / %s" % (counter, num_total))
        counter += 1
        r = Reading.objects.get(id=assoc.reading, entry_id=assoc.entry_id)
        s = Sense.objects.get(id=assoc.sense, entry_id=assoc.entry_id)
        assoc.reading = r.text
        assoc.sense = s.text
        assoc.sense_number = s.sense_id
        assoc.pos = s.pos

        assoc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='pos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='association',
            name='reading',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='association',
            name='sense',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='association',
            name='priorities',
        ),
        migrations.RemoveField(
            model_name='expression',
            name='entry_id',
        ),
        migrations.AddField(
            model_name='association',
            name='sense_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(update_associations),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Sense',
        ),
        migrations.DeleteModel(
            name='ReadingKeyValue',
        ),
        migrations.DeleteModel(
            name='SenseAntonym',
        ),
        migrations.DeleteModel(
            name='SenseCrossRef',
        ),
        migrations.DeleteModel(
            name='SenseKeyValue',
        ),
    ]
