# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180612_0257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='association',
            index_together=set([]),
        ),
    ]
