# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 03:22
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Count


def uniqify_expressions(apps, schema_editor):
    Association = apps.get_model("quiz", "Association")
    Expression = apps.get_model("quiz", "Expression")

    non_unique = (Expression.objects.values_list("text", flat=True)
                  .annotate(text_count=Count("text"))
                  .filter(text_count__gt=1))

    num_total = len(non_unique)
    for i, text in enumerate(non_unique):
        print("%s / %s" % (i, num_total))
        exps = Expression.objects.filter(text=text).order_by("id")
        assocs = Association.objects.filter(expression__text=text)
        exp = exps[0]
        assocs.update(expression=exp)
        for e in exps:
            if e.id == exp.id:
                continue
            assert e.id > exp.id
            e.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180612_0320'),
    ]

    operations = [
        migrations.RunPython(uniqify_expressions),
    ]
