# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.user_models


def copy_expression_text(apps, schema_editor):
    Association = apps.get_model("quiz", "Association")
    Expression = apps.get_model("quiz", "Expression")

    num_total = Association.objects.count()
    for i, assoc in enumerate(Association.objects.all()):
        if not i % 100:
            print("%s / %s" % (i, num_total))
        if assoc.expression is None:
            continue
        exp = Expression.objects.get(id=assoc.expression)
        assoc.expression = exp.text
        assoc.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20180612_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(db_index=True, max_length=75, null=True)),
                ('list_order', models.IntegerField()),
                ('quizlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizList')),
            ],
        ),
        migrations.CreateModel(
            name='UserExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(db_index=True, max_length=75, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('due', models.DateTimeField(default=quiz.user_models.utcnow)),
                ('interval', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='association',
            name='expression',
            field=models.CharField(db_index=True, max_length=75, null=True),
        ),
        migrations.RunPython(copy_expression_text),
        migrations.DeleteModel(
            name='Expression',
        ),
        migrations.DeleteModel(
            name='ExpressionKeyValue',
        ),
        migrations.AlterUniqueTogether(
            name='userexpression',
            unique_together=set([('user', 'expression')]),
        ),
        migrations.AlterUniqueTogether(
            name='quizlistitem',
            unique_together=set([('quizlist', 'list_order'), ('quizlist', 'expression')]),
        ),
    ]
