# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180612_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='text',
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
        migrations.DeleteModel(
            name='ExpressionKeyValue',
        ),
    ]
