# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.user_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20180612_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('due', models.DateTimeField(default=quiz.user_models.utcnow)),
                ('interval', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='expression',
            name='id',
        ),
        migrations.AlterField(
            model_name='expression',
            name='text',
            field=models.CharField(max_length=75, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userexpression',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Expression'),
        ),
        migrations.AddField(
            model_name='userexpression',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizlistitem',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Expression'),
        ),
        migrations.AddField(
            model_name='quizlistitem',
            name='quizlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizList'),
        ),
        migrations.AlterUniqueTogether(
            name='userexpression',
            unique_together=set([('user', 'expression')]),
        ),
        migrations.AlterUniqueTogether(
            name='quizlistitem',
            unique_together=set([('quizlist', 'list_order'), ('quizlist', 'expression')]),
        ),
    ]
