# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_auto_20180617_0529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='association',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='quizlistitem',
            unique_together=set([('quizlist', 'expression'), ('quizlist', 'list_order')]),
        ),
        migrations.AlterUniqueTogether(
            name='userexpression',
            unique_together=set([('user', 'expression')]),
        ),
    ]
