# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20180617_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlist',
            name='name',
        ),
        migrations.AddField(
            model_name='quizlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizlist',
            name='name',
            field=models.CharField(max_length=100, primary_key=False, unique=True),
        ),
    ]
