# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180617_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlistitem',
            name='quizlist',
        ),
        migrations.AddField(
            model_name='quizlistitem',
            name='quizlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizList'),
            preserve_default=False,
        ),
    ]
