# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20180617_0601'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='association',
            unique_together=set([('expression', 'reading', 'sense')]),
        ),
    ]
