# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20180617_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='text',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
