# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20180617_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=24)),
                ('value', models.TextField(db_index=True, default='')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Expression')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=24)),
                ('value', models.TextField(db_index=True, default='')),
                ('entry_id', models.IntegerField(db_index=True)),
                ('reading', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='SenseKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=24)),
                ('value', models.TextField(db_index=True, default='')),
                ('entry_id', models.IntegerField(db_index=True)),
                ('sense_number', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sensekeyvalue',
            unique_together=set([('key', 'value', 'entry_id', 'sense_number')]),
        ),
        migrations.AlterIndexTogether(
            name='sensekeyvalue',
            index_together=set([('key', 'entry_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='readingkeyvalue',
            unique_together=set([('key', 'value', 'entry_id', 'reading')]),
        ),
        migrations.AlterIndexTogether(
            name='readingkeyvalue',
            index_together=set([('key', 'entry_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='expressionkeyvalue',
            unique_together=set([('key', 'value', 'expression')]),
        ),
        migrations.AlterIndexTogether(
            name='expressionkeyvalue',
            index_together=set([('key', 'expression')]),
        ),
    ]
