# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20180617_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionkeyvalue',
            name='entry_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expressionkeyvalue',
            unique_together=set([('key', 'value', 'entry_id', 'expression')]),
        ),
        migrations.AlterIndexTogether(
            name='expressionkeyvalue',
            index_together=set([('key', 'value')]),
        ),
        migrations.AlterIndexTogether(
            name='readingkeyvalue',
            index_together=set([('key', 'value')]),
        ),
        migrations.AlterIndexTogether(
            name='sensekeyvalue',
            index_together=set([('key', 'value')]),
        ),
    ]
