# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20180617_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
